class TypeHelper:
    TEXT = "TEXT"
    TIMESTAMP = "TIMESTAMP"
    NUMERIC = "NUMERIC"
    DOUBLE_PRECISION = "DOUBLE_PRECISION"
    BOOLEAN = "BOOLEAN"
    INTEGER = "INTEGER"
    ARRAY = "ARRAY"
    VARCHAR = "VARCHAR"
